Repository Dario-Maselli/WebDevEssentials, pull requests merged in 2024-08, with the labels that each got.

#3 doc/ai-package-inspirations
  README.md
Labels: documentation

#8 doc/fix-spelling-mistake
  README.md
Labels: documentation

#7 include angular and electron frameworks
  README.md
Labels: Changes Requested

#9 docs/Provide Links To Sites
  .github/workflows/toc.yaml
  .markdownlint.json
  README.md
Labels: documentation

#10 cicd/Self-Hosted Deployment
  .github/workflows/greetings.yml
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/stale.yml
  .github/workflows/toc.yaml
Labels: enhancement

#17 template/Add-Spelling-or-Document-Error-Issue-Template
  .github/ISSUE_TEMPLATE/spelling-or-document-error.md
Labels: bug

#16 template/Add-Feature-Request-Template
  .github/ISSUE_TEMPLATE/feature-request-or-suggestion.md
Labels: suggestion
